FORMAT: 1A
HOST: http://spacerpg.apiblueprint.org/

# SpaceRPG

Polls is a simple API allowing consumers to view polls and vote in them.

## Systems [/systems]

### List All Systems [GET]

+ Response 200 (application/json)

        [
            {
                "Systems": [
                    "Ezo",
                    "Sol",
                    "Terra"
                ]
            }
        ]